
INCLUDES = -I src -I src/include/ -I src/include/sdl3 -I ../../core -I ../../drivers/SDL

all:
	g++ $(INCLUDES) -L src/lib -o main main.cpp -lmingw32 -lSDL3 -lSDL3_ttf -static-libgcc -static-libstdc++

